"""Candidate-layer error codes. Not user-copy and not a search gate."""

from __future__ import annotations

NO_EVIDENCE = "NO_EVIDENCE"
INSUFFICIENT_INFORMATION = "INSUFFICIENT_INFORMATION"
PARSER_ERROR = "PARSER_ERROR"
SCHEMA_ERROR = "SCHEMA_ERROR"
TOOL_ERROR = "TOOL_ERROR"
LLM_ERROR = "LLM_ERROR"
ATTACHMENT_PROCESSING_FAILED = "ATTACHMENT_PROCESSING_FAILED"

GOAL_INCOMPLETE = "GOAL_INCOMPLETE"
